### ISSUE TITLE
[Issue] Docusaurus was unable to resolve the "docusaurus-plugin-react-docgen" plugin.

### ISSUE THREAD

**Issue by caseykhuc** [atomicpages/docusaurus-plugin-react-docgen#15]
After adding plugin config in `docusaurus.config.js`, `docusaurus start` throw this error:

```
Error: Docusaurus was unable to resolve the "docusaurus-plugin-react-docgen" plugin. Make sure one of the following packages are installed:
- docusaurus-plugin-react-docgen
- @docusaurus/plugin-docusaurus-plugin-react-docgen
- docusaurus-plugin-docusaurus-plugin-react-docgen
```

Config used:
```js
{
  plugins: [
    [
      "docusaurus-plugin-react-docgen",
      {
        src: [path.join(__dirname, "../../aha-react/src/components")],
        route: {
          path: "/docs/components",
          component: require.resolve("./src/components/PropTable.tsx"),
          exact: true,
        },
      },
    ],
  ]
}
```

I also went to check node_modules and the package is already installed 🤔 Any clues to resolve this? Thanks in advance!
![image](https://github.com/atomicpages/docusaurus-plugin-react-docgen-typescript/assets/10876529/232e72b6-97fc-4c8d-8544-bc886b60c9d9)

**Comment by andrew-hm** [comment]
there's no main in the package and the dist folder is not published with the package is the issue

**Comment by atomicpages** [comment]
@caseykhuc, @andrew-hm apologies for the delay. Somehow this slipped through my notifications. A fixed has been deployed to `0.1.1` of the package. Try it out and LMK!

**Comment by atomicpages** [comment]
Fixed in 60d810831595a5596b3f6451bde651f28139eee0

**Comment by andrew-hm** [comment]
you also have to add the options for react-docgen, then update the api to its parse method. I think this has a long way to go because after its all set and done you only get the response back from react-docgen. we need templates and the rest of the structure to get it somewhere near feature rich as react-styleguidist, some day soon, its very promising start!!

**Comment by atomicpages** [comment]
@andrew-hm feel free to make more issues/PRs! Happy to review/collaborate on new features 👌
